### ISSUE TITLE
.NET core/ .NET 5 version

### ISSUE THREAD

**Issue by szolkowski** [jaerith/ONIX-Data#10] opened 2021-06-11 07:06 UTC
Hello,

First of all I must say great work with this library!

1. Is there any known problem/issues/blocker with porting this library to .NET core from classic .NET framework? 
2. Do you accept contributions to your repo?

**Comment by jaerith** [comment] 2021-06-11 16:57
1.) That's a good question.  My first thought would be that it's entirely possible and that it shouldn't require that much work.  But...much like other platforms, Microsoft is probably not focusing on XML for support as time goes on.  So I do worry about changes made for Core, especially if they affect performance.  (To be honest, their current support for XML and DTDs isn't exactly wonderful.)  It would require a little work and some regression testing to be sure.

2.) Absolutely!  And if you're interesting in creating a OnixDataCore project and adding it to this solution, I'm all for it.  :)

**Comment by szolkowski** [comment] 2021-06-14 06:50
1. Could you provide some onix files for testing and benchmarking performance?
2. OnixTextContent.cs seems to be duplicated - is there a reason for it?

**Comment by jaerith** [comment] 2021-06-14 18:22
1.) I do have some files for regression testing, but unfortunately, they're proprietary.  And publishers are a little touchy about sharing their files, even with something so mundane as simple book data.  I might be able to clean the files and turn them into something generic, but that might take some time.

2.) Ah ha - good catch!  I got rid of the extra file.  It's gone now.

**Comment by szolkowski** [comment] 2021-06-18 12:02
I was playing with best way to manage library for both .NET core and classic .NET framework and I think that way to go is to convert project to .NET standard in correct version and it will be correctly working for both core classic. 

The only drawback is that it requires updating minimal .NET classic version for this library to 4.6.2 from current 4.5.2. Do you think this is a problem or do we can go with this?

WiP branch on my fork https://github.com/Stanislaw000/ONIX-Data/tree/feature/migrate-library-to-net-standard
Some of samples doesn't work for both cases (library missing support), but it doesn't seems to have any regressions.

Later I will prepare some tests for benchmarking performance, so you will be able easily test it against your proprietary files and check performance.

**Comment by jaerith** [comment] 2021-06-18 15:12
Some of your samples don't work?  For both cases of what?  Reference and short?  2.1 and 3.0?

Thanks for putting this out there!  I'll take a look when I have some time in the near future, probably next week.

**Comment by szolkowski** [comment] 2021-06-18 18:22
I have used too many logical shortcuts, sorry.

I am using right now 4 sample files from 3.0.7 format specification and 2 of the samples have xml errors pre-migrations already.

"Onix3sample_refnames" and "Onix3sample_shorttags", however I tested this also on some proprietaryOnix files and seems to be working good after migrations.

Do you agree with my approach that we can replace current 4.5.2 project with .NET standard 2.0, so there will single code base that will work with both core nad classic .NET Framework (4.6.2+)?

**Comment by jaerith** [comment] 2021-06-20 20:16
Sounds good.  I'll create a branch called NetStandard, and that can be the experimental ground to which we can contribute.

**Comment by szolkowski** [comment] 2021-06-21 09:57
I have added benchmarks based on artificial data files which works for V3 parser, but doesn't for legacy one. Benchmarks can be easily changed/modified for better testing.

PR with changes: #12

**Comment by jaerith** [comment] 2021-06-22 15:35
Very nice!  My schedule is a little full now, but when I have some time, I'll try it out and run some of my own tests.

**Comment by jaerith** [comment] 2021-06-28 21:35
I took a look at the code and ran the benchmark test.  Looks great!  When I have more time, I'll add some tests for the legacy stuff (<= ONIX 2.1).

**Comment by jaerith** [comment] 2021-06-28 22:03
One question: is the OnixData.Standard.CoreTests project supposed to target the .NET 5.0 framework?

**Comment by szolkowski** [comment] 2021-06-29 08:44
Yes, I think it is best to go with newest stable versions instead of locking on 3.x version, but we can also add tests for this framework versions.
Thanks to having lib as .NET standard we have all these versions anyway :)

**Comment by jaerith** [comment] 2021-07-09 19:55
The benchmark tests are interesting.  Not only do large files seem to gradually perform worse with each newer .NET framework, but it seems that .NET Core is especially worse, being 25% slower.

It seems that whatever changes being done by Microsoft to improve the general framework are at the expense of XML.  :)

**Comment by szolkowski** [comment] 2021-07-11 07:36
Thats interesting to know - I wasn't expecting such big differences. How's .NET 5 was doing in these benchmarks? Could you post here results?

Thank for benchmarking it!

**Comment by jaerith** [comment] 2021-07-12 21:59
Unfortunately, .NET 5 also suffered from being slightly less performant.  Obviously, these sample files are not very big, and the difference is actually slight in terms of time spent parsing.  However, with larger files (especially > 1 GB), this issue would obviously become more pronounced, resulting in minutes being lost due to being less performant.

It's only conjecture, but I suspect that larger files (like > 250 MB) will actually have gaps of more than a few minutes between framework tests, due to an additional factor.  The ONIX-Data project loads smaller files (< 250 MB) into memory before parsing them, in order to be even faster.   With larger files, the iteration (from parsing) takes place within the file, in order to minimize the memory overhead.  (This is also necessary since larger strings in memory cause OutOfMemory exceptions to be thrown from .NET when using the standard parsing libraries).  I'm inclined to think that this will exacerbate the current issue that can be seen here.

This could be an argument for the ONIX standard to move towards JSON, since the rest of the world is leaving XML behind.  But I doubt that the EDITEUR organization will be shifting to JSON anytime soon.

|       Method |                  Job |            FileName |        Mean |     Error |    StdDev | Ratio | RatioSD |
|------------- |--------------------- |-------------------- |------------:|----------:|----------:|------:|--------:|
|     V3Parser |             .NET 5.0  | Sample-500-Products |  1,919.2 ms |  32.58 ms |  28.88 ms |  1.01 |    0.02 |
|     V3Parser |      .NET Core 3.1 | Sample-500-Products |  2,391.8 ms |  47.38 ms |  61.60 ms |  1.26 |    0.05 |
|     V3Parser |  .NET Framework 4.6.2 | Sample-500-Products |  1,902.9 ms |  35.19 ms |  45.76 ms |  1.00 |    0.00 |
|     V3Parser |  .NET Framework 4.8 | Sample-500-Products |  1,909.6 ms |  37.11 ms |  36.44 ms |  1.00 |    0.03 |

|       Method |                  Job |          FileName |        Mean |     Error |    StdDev | Ratio | RatioSD |
|------------- |--------------------- |-------------------- |------------:|----------:|----------:|------:|--------:|
| LegacyParser |  .NET 5.0 | Sample-500-Products |  8,662.8 ms | 127.08 ms | 118.87 ms |  1.06 |    0.02 |
| LegacyParser |  .NET Core 3.1 | Sample-500-Products | 10,296.9 ms | 182.54 ms | 267.56 ms |  1.27 |    0.05 |
| LegacyParser |  .NET Framework 4.6.2 | Sample-500-Products |  8,191.1 ms | 130.37 ms | 121.95 ms |  1.00 |    0.00 |
| LegacyParser |  .NET Framework 4.8 | Sample-500-Products |  8,446.8 ms | 167.73 ms | 218.10 ms |  1.04 |    0.03 |

**Comment by jaerith** [comment] 2021-07-12 22:02
> Thats interesting to know - I wasn't expecting such big differences. How's .NET 5 was doing in these benchmarks? Could you post here results?
> 
> Thank for benchmarking it!

Thanks for taking the time to set up a proper benchmark environment!

**Comment by szolkowski** [comment] 2021-07-13 08:02
Whats the plan regarding this change? Will you merge it to main branch and replace old .NET project with .NET standard one and make new Nuget version for it?

**Comment by jaerith** [comment] 2021-07-13 18:45
Yes, I aim to merge this branch into the main, once I have added a bit more code for Legacy in the sections of benchmarking and base tests.  Since you've led the way in making it a more organized project, I want to complete the picture.  :)  I also planned on creating a separate Nuget package for the Standard library that will exist alongside the current Nuget package, for the time being.  Eventually, it should replace the current Nuget package.

I was also dabbling with the thought of investigating this performance issue, since I know a few people who are more up-to-date on the latest idiosyncratic changes to the framework.  Maybe they could provide some guidance.

**Comment by szolkowski** [comment] 2021-07-14 06:22
Regarding .NET core perfomance degradation, .NET 5 is newest version of .NET core (could be name .NET core 4.0 also, but they skip it for different reasons) and I am not sure if it makes sense to make XML optimization for .NET core 3.1 since there is hardly any reason why not to use .NET 5 instead.

Great to hear that you want to merge it to the main. I am just concerned with having 2 project with the same logic ( standard vs old one), because all changes will be needed to be done twice. Standard version can be target both vs 4.6.2 framework and .NET 5 also, so I think it might be better to have just it, but it is of course your call :)

**Comment by jaerith** [comment] 2021-07-14 16:18
From what I remember, they went with .NET 5 in order to stop the confusion with Framework vs. Core, which makes sense.

Oh yes, having two projects with the same logic is never a good thing.  Thankfully, updates to this project are not that common, so it's less of an issue.  One Standard project will definitely be the end goal.  Due to some distractions in my personal life (that are ongoing for the next couple months), progress here will be a tad slow.  However, we'll eventually get there.

**Comment by szolkowski** [comment] 2021-07-28 12:15
I have added some improvements to NetStandard branch in pr #16 :

1. Added missing properties for short tags and a helper method from classic project to NetStandard one that were done outside pr #13 .
2.Add new explicit project for NET 5 unit tests and change core test project to .core 3.1. This should be less confusing. Clear up tests and fix namespaces.

**Comment by jaerith** [comment] 2021-08-06 19:37
Thanks for all the bells and whistles!  Unit testing and code coverage...now everybody knows how lazy I am in my personal time.  :)  But seriously, thanks for all the work to improve the project.  It is really appreciated!

Two quick questions:

1. I'm not that familiar with CodeQL, but you know what this means in the analysis report?

```
| Severity |                                            Message                                             |
+----------+------------------------------------------------------------------------------------------------+
| error    | Unexpected C# extractor error: Uncaught exception. The method or operation is not implemented. |

```

2. Did you change the actions to upload results and then invoke code coverage analysis because the code coverage requires the upload step?  Since I'm not familiar with these actions, I'm just curious.

Thanks again!  I think that we're getting to the finish line with this branch.

**Comment by jaerith** [comment] 2021-08-06 20:55
Hmmm...think that we should create anything to support CI via Azure Pipelines?  Or do you consider Azure Pipelines to be redundant at this point?

**Comment by szolkowski** [comment] 2021-08-07 16:14
Thanks for liking new changes! I am still working on improving Code Coverage workflows to fully work, but it seems there are some problem in action doing it - I have opened issue and waiting for that action maintainer to response. https://github.com/zgosalvez/github-actions-report-lcov/issues/9

1. I don't know what it is - I am also not familiar with it - maybe we should use Sonarcloud for analysis? Sonarqube have very nice C# analysis.
2. I have read more into permission model for public repo forking and there is not possible for PR from fork to obtain write access token (security - if it would be possible then anybody could print secrets from main repo), so both tests results and code coverage would crash. I haven't spotted it earlier, because it is working inside a single repo.
The workaround for this is to make on PR branch build, tests and uploading results and then trigger workflow on default branch that will process these files, since default branch have writing token access, because it doesn't come from fork.
3. I think that Azure pipeline are redundant since, we can do anything with Github actions/workflows I think.

**Comment by szolkowski** [comment] 2021-08-09 15:58
I was playing with SonarCloud and it seems to be working fine:

Example PR: https://github.com/Stanislaw000/ONIX-Data/pull/11
Project analysis on SonarCloud: https://sonarcloud.io/dashboard?id=Onix-Data-S-fork

Cool badges that can be added to Readme:
https://github.com/Stanislaw000/ONIX-Data
![image](https://user-images.githubusercontent.com/44289106/128736696-df791c3d-41a1-4dbe-b8e3-42db742f29f9.png)

**Comment by jaerith** [comment] 2021-08-09 22:41
First, I'm surprised that ONIX-Data scored as well as it did, since I've never really run it through a quality analysis like SonarKube.  Who would think - my stuff actually works!  :)  But I'll definitely look at the issues that it's pointing out.

Also - I'm really digging Github Actions!  I had no idea that there was so much functionality available, including the integration into SonarKube.  I'll create my own SonarKube account, so I can start incorporating it into the CI and the docs.

Thanks for all the investigation and hard work!

**Comment by jaerith** [comment] 2021-08-09 23:30
Oops...I mean SolarCloud account.  In any case, your recent changes for test-report.yml and sonarcloud.yml look good to me!

**Comment by szolkowski** [comment] 2021-08-10 07:03
I am glad that you like these ideas! Below I have added instruction, that I think should be enough to have working solution that can be future upgraded and more customize.

If you are looking for some SonarQube materials, then you may like series of my SonarQube articles: https://blog.setapp.pl/sonarqube_introduction - they have aged a little, but a lot of configuration stuff with customizing analysis scope, exclusions etc. are still there across different parts.

What needs to be to on your end to integrate SonarCloud:

1. Create SonarCloud account
2. Create organization (free plan) bind to your GitHub (binding is needed for SonarCloud bot comments)
3. Create access token in SonarCloud https://sonarcloud.io/account/security/
4. Add this token as secret to repo under name: SONAR_TOKEN
5. In sonarcloud.yml update line 36 with your organization key and project key: `dotnet sonarscanner begin /o:onix-data-test-org /k:Onix-Data-S-fork ......` (values after /o: and /k:). I think that cleaner solution here might be to create repo secrets for this and use them to pass these values - secrets usage syntax in workflow is: "${{ secrets.SECRETS_NAME }}" 
6. (Not sure if this step can be done before first analysis) Rename default branch in SonarCloud project from master to NetStandard.
7.  Update badges addresses with link to your SonarCloud instance

PRs:

1. #21 adding reporter to default branch - I have removed old code coverage since, it doesn't meet needs in reporting for public repo and we have coverage in SonarCloud anyway. (details inside PR)
2. #22 Improve workflow logic and add SonarCloud integration  - after going with instruction above next runs should pass - currently it is failing on missing access token from repo secrets.

**Comment by jaerith** [comment] 2021-08-11 15:23
Is something not working with the pull for SonarCloud integration?  I saw that one of the checks failed.

**Comment by szolkowski** [comment] 2021-08-11 16:20
As I have wrote above, it needs to be configured by repository owner - check instruction after "What needs to be to on your end to integrate SonarCloud:" - without configuration SonarCloud integration will fail.

Steps from 1 to 5 are required for SonarCloud workflow to make it work and not failed..

**Comment by jaerith** [comment] 2021-08-11 16:53
Whoops!  I hadn't read the post above yet.  Things are a little hectic on my end, but I'll be sure to take a look when I have a moment.

**Comment by jaerith** [comment] 2021-08-13 19:31
I was able to get SonarCloud working with your excellent directions. I'll read your other posts about SonarCloud, when I have more time.  Looks great, especially with those badges!  Very cool!

I do like shiny things.  "Look Mom, I got a gold star!"  :)

**Comment by szolkowski** [comment] 2021-08-16 06:27
I am glad that you like it :)

Is there any roadmap for creating one way or another .NetStandard nuget package?

**Comment by jaerith** [comment] 2021-08-16 14:16
Yes, I was planning to merge this branch into the main within the next couple weeks, and then after that, upload the ONIX-Data package for Standard .NET.

Or, when you say 'roadmap', do you mean an automated solution, like one for a CI pipeline that automatically uploads Github builds to Nuget.org?

**Comment by szolkowski** [comment] 2021-08-17 10:13
First one, but making automate solution would be also nice.

**Comment by jaerith** [comment] 2021-08-18 01:46
I was trying to get the test coverage up to 50%, but I'll accept over 40% at this point.

Did you need the new Nuget package uploaded for a CI pipeline at work?  I can always upload the package sooner, if it'd help you out.

**Comment by szolkowski** [comment] 2021-08-18 07:51
Thanks for informations!

I can wait for proper package - right now I have  locally compiled dll included into repo which works fine with everything - just in longer run it is always better to have 3rd party libs added as packages instead :)

**Comment by jaerith** [comment] 2021-08-30 20:11
The branch has been merged.  Huzzah!

**Comment by jaerith** [comment] 2021-08-30 20:14
Spoke too soon.  There are a few things that I need to fix, in order to get the CI working.  But we're pretty close now, at least.

**Comment by jaerith** [comment] 2021-08-30 22:14
And now, the Standard version of the library is now on Nuget:

https://www.nuget.org/packages/ONIX-Data.Standard/0.5.2

**Comment by jaerith** [comment] 2021-08-31 17:41
Thanks for that pull request, @Stanislaw000!  Now the CI with SonarCloud is working as well.  Well done!

**Closed as completed** 2021-08-31 17:41 UTC
Labels: question
